import { ArrowRight, BarChart3, Brush, Clock3, Code2, Heart, Lightbulb, MessageCircle, Rocket, Target, TrendingUp, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import logo from '../assets/logo.png';
import { showcaseApps } from '../components/home/data';
import SiteHeader from '../components/SiteHeader';

const nav = [['Our Work','/work'],['Why Us','/why-us'],['Process','/process'],['Contact','/contact']];
const projects = [
  {...showcaseApps[2],type:'Fashion',tone:'peach',blurb:'Fashion production and order management for a modern fashion house.'},
  {...showcaseApps[1],type:'Food',tone:'cream',blurb:'Pastry business management from orders to delivery.'},
  {...showcaseApps[3],type:'Beauty',tone:'pink',blurb:'Salon booking and business management for modern beauty businesses.'},
  {...showcaseApps[0],type:'E-commerce',tone:'silver',blurb:'A simple commerce platform for home and kitchen appliances.'},
  {...showcaseApps[4],type:'Creator',tone:'sand',blurb:'A creator platform for building community and monetising content.'},
];

function Phone({project,className=''}){return <div className={`phone ${className}`}><div className="phone-notch"/><div className="phone-screen" style={{backgroundImage:`linear-gradient(to top,rgba(4,15,28,.78),transparent 62%),url(${project.image})`}}><strong>{project.name}</strong><div><h3>{project.tagline}</h3><button>{project.cta}</button></div></div></div>}
function Hero(){return <main className="hero"><div className="hero-copy"><span className="eyebrow">SOFTWARE THAT FITS YOUR BUSINESS</span><h1>We build <em>software</em><br/>people actually<br/>want to use.</h1><p>Custom platforms designed around how your business actually works.</p><div className="hero-actions"><Link className="button primary" to="/work">View Our Work <ArrowRight/></Link><Link className="button secondary" to="/contact">Build With Us</Link></div><div className="micro-proof"><span>Based in Nigeria</span><span>•</span><span>Built for the world</span></div></div><div className="hero-visual"><div className="orange-orbit"/><div className="phone-fan">{projects.map((p,i)=><Phone project={p} key={p.name} className={`phone-${i+1}`}/>)}</div><span className="script-note">Ideas<br/>Built<br/>Beautifully</span></div></main>}
function Highlights(){const items=[[Clock3,'Save Time'],[BarChart3,'Work Smarter'],[Users,'Grow Faster'],[Heart,'Happier Customers']];return <section className="highlights">{items.map(([Icon,l])=><div key={l}><Icon/><span>{l}</span></div>)}</section>}
function Work(){return <section className="section work" id="work"><div className="section-heading"><div><span className="eyebrow">OUR WORK</span><h2>Real businesses.<br/><em>Real platforms.</em></h2></div><p>We create considered digital products that make ambitious businesses easier to run—and easier to love.</p></div><div className="filters"><button className="active">All</button>{['Fashion','Food','Beauty','E-commerce','Creator'].map(x=><button key={x}>{x}</button>)}</div><div className="project-grid">{projects.map((p,i)=><article className={`project-card ${i===4?'wide':''}`} key={p.name}><div className={`project-image ${p.tone}`} style={{backgroundImage:`linear-gradient(90deg,rgba(255,255,255,.12),transparent),url(${p.image})`}}><Phone project={p}/><span>{p.type}</span></div><div className="project-info"><div><small>0{i+1} / {p.type}</small><h3>{p.name}</h3><p>{p.blurb}</p></div><a href="#contact" aria-label={`View ${p.name}`}><ArrowRight/></a></div></article>)}</div></section>}
function WhyUs(){const reasons=[[Target,'Understand your business','We start with your world, your customers and the way your team really works.'],[Brush,'Beautiful design','Every screen is clear, intuitive and carefully designed around real people.'],[TrendingUp,'Real results','We build tools that save time, unlock growth and keep delivering value.']];return <section className="why section" id="why-us"><div className="why-art"><div className="portrait" style={{backgroundImage:`url(${showcaseApps[3].image})`}}/><Phone project={showcaseApps[2]}/><span className="script-note dark">Real businesses.<br/>Real impact.</span></div><div className="why-copy"><span className="eyebrow">WHY CHOOSE SATOSHI</span><h2>More than<br/>developers.<br/><em>Your business<br/>partner.</em></h2><p className="lead">We turn your ideas into software that works in the real world.</p><div className="reason-list">{reasons.map(([Icon,t,x])=><div className="reason" key={t}><span><Icon/></span><div><h3>{t}</h3><p>{x}</p></div></div>)}</div></div></section>}
function Process(){const steps=[[MessageCircle,'Discover','We learn about your business, goals and challenges.'],[Target,'Scope','We map the workflow, features and requirements.'],[Brush,'Design','We create a beautiful and intuitive product experience.'],[Code2,'Develop','We build, test and refine your platform.'],[Rocket,'Launch','We deploy and support you as you grow.']];return <section className="process section" id="process"><div className="section-heading"><div><span className="eyebrow">HOW WE WORK</span><h2>A simple process<br/>from <em>idea to impact.</em></h2></div><p>We keep it simple, structured and transparent so you always know what’s next.</p></div><div className="process-grid">{steps.map(([Icon,t,x],i)=><article key={t}><span className="step-no">0{i+1}</span><Icon/><h3>{t}</h3><p>{x}</p></article>)}</div><div className="scope-card"><div><span className="eyebrow">THE SCOPE PROCESS</span><h3>A solid plan<br/><em>before we build.</em></h3><p>In a little under two weeks, we turn your idea into a clear product blueprint.</p><a href="#contact" className="button primary">Start Your Scope <ArrowRight/></a></div><div className="scope-map">{[Lightbulb,Users,MessageCircle,Code2].map((Icon,i)=><span key={i}><Icon/></span>)}<i/><i/><i/></div></div></section>}
function Contact(){return <><section className="contact" id="contact"><span className="eyebrow">HAVE AN IDEA?</span><h2>Let’s build something<br/><em>amazing together.</em></h2><p>Tell us what you’re working on. We’ll help you find the clearest path from idea to impact.</p><a className="button light" href="mailto:hello@satoshicomms.com">Start Your Project <ArrowRight/></a></section><footer><img src={logo} alt="Satoshi Communications"/><p>Business ideas. <b>Real solutions.</b></p><div>{nav.slice(1).map(([l,h])=><a href={h} key={l}>{l}</a>)}</div><small>© {new Date().getFullYear()} Satoshi Communications. Built beautifully.</small></footer></>}
export default function Home(){return <div className="page"><SiteHeader/><Hero/><Highlights/><Work/><WhyUs/><Process/><Contact/></div>}
