import { ArrowRight, BarChart3, ShoppingBag } from 'lucide-react';
import { Link } from 'react-router-dom';
import SiteHeader from '../components/SiteHeader';

const projects=[
  {number:'01',name:'Jeets & Cream',type:'Commerce + Operations',title:'Sweet moments. Serious software.',description:'A complete pastry-commerce ecosystem connecting a polished customer store to order management, customer conversations, delivery and reporting.',to:'/work/jeets-and-cream',image:'/projects/jeets-and-cream/customer-home.png',second:'/projects/jeets-and-cream/admin-dashboard.png',className:'portfolio-jeets',Icon:ShoppingBag,tags:['Customer storefront','Admin platform','Paystack checkout']},
  {number:'02',name:'FreshFold',type:'Laundry Operations',title:'Clean operations. Brighter business.',description:'An end-to-end laundry platform that moves every order from intake through washing, quality control, delivery and business reporting.',to:'/work/freshfold',image:'/projects/freshfold/dashboard.png',second:'/projects/freshfold/quality-check.png',className:'portfolio-fresh',Icon:BarChart3,tags:['8-stage workflow','Quality control','Business reports']},
];

export default function WorkIndex(){return <div className="portfolio-page"><SiteHeader/><main className="portfolio-main"><div className="portfolio-heading"><div><span className="eyebrow">OUR PORTFOLIO</span><h1>Real businesses.<br/><em>Real solutions.</em></h1></div><p>Purpose-built platforms shaped around the people, processes and ambitions behind each business.</p></div><div className="portfolio-list">{projects.map(({Icon,...p})=><article className={`portfolio-entry ${p.className}`} key={p.name}><div className="portfolio-copy"><div className="portfolio-meta"><span>{p.number}</span><span><Icon/> {p.type}</span></div><h2>{p.name}</h2><h3>{p.title}</h3><p>{p.description}</p><div className="portfolio-tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><Link className="button portfolio-button" to={p.to}>Explore case study <ArrowRight/></Link></div><Link to={p.to} className="portfolio-art" aria-label={`View ${p.name}`}><div className="portfolio-glow"/><img src={p.image} alt={`${p.name} primary screen`}/><img src={p.second} alt={`${p.name} secondary screen`}/><span><ArrowRight/></span></Link></article>)}</div></main><section className="portfolio-cta"><span className="eyebrow">YOUR BUSINESS COULD BE NEXT</span><h2>Let’s create work<br/>worth showing off.</h2><Link className="button light" to="/contact">Start your project <ArrowRight/></Link></section></div>}
