import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, ChevronLeft, ChevronRight, ShoppingBag, Sparkles, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import SiteHeader from '../components/SiteHeader';

const customer=[
  ['customer-home.png','Storefront','Browse favourites and discover new treats.'],['product-details.png','Product detail','Choose size, quantity and review ingredients.'],['cart.png','Cart','Review items and see transparent totals.'],['checkout.png','Checkout','Flexible delivery and secure Paystack payment.'],['order-confirmed.png','Order tracking','A reassuring confirmation and live order journey.'],
];
const admin=[
  ['admin-dashboard.png','Command centre','Today’s orders, production and delivery at a glance.'],['admin-order.png','Order management','Customer, payment and fulfilment details in one place.'],['admin-chat.png','Connected conversations','Respond to customers without losing order context.'],['admin-delivery.png','Delivery history','A complete view of fulfilment and customer feedback.'],['admin-inbox.png','Unified inbox','WhatsApp, Instagram, email and calls together.'],['admin-reports.png','Business reports','Clear performance data for better decisions.'],
];

function Showcase(){const[group,setGroup]=useState('customer');const[index,setIndex]=useState(0);const list=group==='customer'?customer:admin;useEffect(()=>setIndex(0),[group]);const move=d=>setIndex(i=>(i+d+list.length)%list.length);return <div className="case-showcase"><div className="showcase-tabs"><button className={group==='customer'?'active':''} onClick={()=>setGroup('customer')}><ShoppingBag/> Customer experience</button><button className={group==='admin'?'active':''} onClick={()=>setGroup('admin')}><BarChart3/> Admin platform</button></div><div className="carousel-stage"><button className="carousel-arrow left" onClick={()=>move(-1)} aria-label="Previous screen"><ChevronLeft/></button><div className="screen-stack">{[-1,0,1].map(offset=>{const i=(index+offset+list.length)%list.length;return <button onClick={()=>offset&&move(offset)} className={`case-screen screen-${offset+1}`} key={`${group}-${i}-${offset}`}><img src={`/projects/jeets-and-cream/${list[i][0]}`} alt={list[i][1]}/></button>})}</div><button className="carousel-arrow right" onClick={()=>move(1)} aria-label="Next screen"><ChevronRight/></button></div><div className="screen-caption"><span>{String(index+1).padStart(2,'0')} / {String(list.length).padStart(2,'0')}</span><div><h3>{list[index][1]}</h3><p>{list[index][2]}</p></div></div><div className="carousel-dots">{list.map((x,i)=><button aria-label={`View ${x[1]}`} className={i===index?'active':''} onClick={()=>setIndex(i)} key={x[0]}/>)}</div></div>}

export default function Work(){return <div className="case-page"><SiteHeader/><section className="case-hero"><div className="case-crumb"><Link to="/"><ArrowLeft/> Back home</Link><span>01 / Featured project</span></div><div className="case-title"><div><span className="eyebrow">JEETS &amp; CREAM</span><h1>Sweet moments.<br/><em>Serious software.</em></h1></div><p>We designed a complete pastry-commerce ecosystem: a polished customer store and a powerful operations platform built around how the team actually works.</p></div><div className="case-feature"><div className="case-feature-copy"><span>THE RESULT</span><h2>One platform.<br/>Every order,<br/>beautifully handled.</h2><div className="case-stats"><div><b>2</b><small>Connected experiences</small></div><div><b>11</b><small>Core product screens</small></div><div><b>1</b><small>Unified business</small></div></div></div><div className="case-feature-art"><img src="/projects/jeets-and-cream/customer-home.png" alt="Jeets and Cream customer app"/><img src="/projects/jeets-and-cream/admin-dashboard.png" alt="Jeets and Cream admin dashboard"/><span>Freshly built.<br/>Beautifully useful.</span></div></div></section><section className="case-story"><span className="eyebrow">THE PRODUCT</span><h2>From first craving<br/>to final delivery.</h2><p>Explore the customer and admin journeys. Use the arrows, dots, or the neighbouring screens to move through the experience.</p><Showcase/></section><section className="case-outcomes"><article><Sparkles/><h3>A memorable storefront</h3><p>Editorial food imagery and frictionless shopping make every product feel irresistible.</p></article><article><Users/><h3>Customer context</h3><p>Orders and conversations stay connected, so service feels personal at every step.</p></article><article><BarChart3/><h3>Operational clarity</h3><p>Production, delivery and reporting give the team one source of truth.</p></article></section><section className="next-project"><div><span className="eyebrow">NEXT PROJECT</span><h2>More real solutions<br/>coming soon.</h2></div><Link className="button light" to="/contact">Start yours <ArrowRight/></Link></section></div>}
