import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, ChevronLeft, ChevronRight, Shirt, ShoppingBag, Sparkles, Users } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import SiteHeader from '../components/SiteHeader';

const jeetsCustomer=[['customer-home.png','Storefront','Browse favourites and discover new treats.'],['product-details.png','Product detail','Choose size, quantity and review ingredients.'],['cart.png','Cart','Review items and see transparent totals.'],['checkout.png','Checkout','Flexible delivery and secure Paystack payment.'],['order-confirmed.png','Order tracking','A reassuring confirmation and live order journey.']];
const jeetsAdmin=[['admin-dashboard.png','Command centre','Today’s orders, production and delivery at a glance.'],['admin-order.png','Order management','Customer, payment and fulfilment details in one place.'],['admin-chat.png','Connected conversations','Respond to customers without losing order context.'],['admin-delivery.png','Delivery history','A complete view of fulfilment and customer feedback.'],['admin-inbox.png','Unified inbox','WhatsApp, Instagram, email and calls together.'],['admin-reports.png','Business reports','Clear performance data for better decisions.']];
const freshfoldFlow=[['dashboard.png','Operations dashboard','Orders, revenue and urgent issues are visible at a glance.'],['new-order.png','Fast order capture','Build detailed laundry orders in a few focused steps.'],['order-passport.png','Order passport','Every garment follows a transparent operational journey.'],['orders.png','Order management','Filter and track every customer order by status.'],['washing-floor.png','Washing floor','Keep production flowing with clear stage ownership.'],['quality-control.png','Quality control','Inspect work and surface anything needing attention.'],['quality-check.png','Quality approval','A practical checklist protects service quality.'],['ready-delivery.png','Ready and delivery','Schedule handoffs without losing customer context.'],['schedule-delivery.png','Delivery scheduling','Confirm delivery details and notify the customer.'],['delivery-complete.png','Completion','Close the loop with proof, notes and confirmation.'],['reports.png','Business reports','Turn daily operations into useful business insight.']];

const projects={
  jeets:{folder:'jeets-and-cream',eyebrow:'JEETS & CREAM',title:'Sweet moments.',accent:'Serious software.',intro:'We designed a complete pastry-commerce ecosystem: a polished customer store and a powerful operations platform built around how the team actually works.',result:['One platform.','Every order,','beautifully handled.'],images:['customer-home.png','admin-dashboard.png'],stats:[['2','Connected experiences'],['11','Core product screens'],['1','Unified business']],groups:[['customer','Customer experience',ShoppingBag,jeetsCustomer],['admin','Admin platform',BarChart3,jeetsAdmin]],story:['THE PRODUCT','From first craving','to final delivery.'],outcomes:[[Sparkles,'A memorable storefront','Editorial food imagery and frictionless shopping make every product feel irresistible.'],[Users,'Customer context','Orders and conversations stay connected, so service feels personal at every step.'],[BarChart3,'Operational clarity','Production, delivery and reporting give the team one source of truth.']],next:['FRESHFOLD','Clean operations. Brighter business.','/work/freshfold'],note:'Freshly built. Beautifully useful.'},
  freshfold:{folder:'freshfold',eyebrow:'FRESHFOLD',title:'Clean operations.',accent:'Brighter business.',intro:'We built an end-to-end laundry operations platform that moves every order clearly from intake to washing, quality control, delivery and reporting.',result:['A cleaner way','to run the','whole business.'],images:['dashboard.png','quality-check.png'],stats:[['8','Workflow stages'],['11','Core product screens'],['1','Connected operation']],groups:[['flow','Operations workflow',Shirt,freshfoldFlow]],story:['THE PLATFORM','From drop-off','to fresh delivery.'],outcomes:[[Shirt,'Workflow built in','Every order moves through a visible, structured process from intake to completion.'],[Sparkles,'Quality protected','Purpose-built checks help the team deliver consistently excellent care.'],[BarChart3,'Decisions made clearer','Revenue, volume and operational performance live in one useful view.']],next:['JEETS & CREAM','Sweet moments. Serious software.','/work/jeets-and-cream'],note:'Clean people. Happier days.'}
};

function Showcase({project}){const[group,setGroup]=useState(project.groups[0][0]);const[index,setIndex]=useState(0);const active=project.groups.find(x=>x[0]===group)||project.groups[0];const list=active[3];useEffect(()=>{setGroup(project.groups[0][0]);setIndex(0)},[project]);const move=d=>setIndex(i=>(i+d+list.length)%list.length);return <div className="case-showcase"><div className="showcase-tabs">{project.groups.map(([id,label,Icon])=><button key={id} className={group===id?'active':''} onClick={()=>{setGroup(id);setIndex(0)}}><Icon/> {label}</button>)}</div><div className="carousel-stage"><button className="carousel-arrow left" onClick={()=>move(-1)} aria-label="Previous screen"><ChevronLeft/></button><div className="screen-stack">{[-1,0,1].map(offset=>{const i=(index+offset+list.length)%list.length;return <button onClick={()=>offset&&move(offset)} className={`case-screen screen-${offset+1}`} key={`${group}-${i}-${offset}`}><img src={`/projects/${project.folder}/${list[i][0]}`} alt={list[i][1]}/></button>})}</div><button className="carousel-arrow right" onClick={()=>move(1)} aria-label="Next screen"><ChevronRight/></button></div><div className="screen-caption"><span>{String(index+1).padStart(2,'0')} / {String(list.length).padStart(2,'0')}</span><div><h3>{list[index][1]}</h3><p>{list[index][2]}</p></div></div><div className="carousel-dots">{list.map((x,i)=><button aria-label={`View ${x[1]}`} className={i===index?'active':''} onClick={()=>setIndex(i)} key={x[0]}/>)}</div></div>}

export default function Work(){const isFresh=useLocation().pathname.includes('freshfold');const p=isFresh?projects.freshfold:projects.jeets;return <div className={`case-page ${isFresh?'freshfold-case':''}`}><SiteHeader/><section className="case-hero"><div className="case-crumb"><Link to="/"><ArrowLeft/> Back home</Link><span>{isFresh?'02':'01'} / Featured project</span></div><div className="case-title"><div><span className="eyebrow">{p.eyebrow}</span><h1>{p.title}<br/><em>{p.accent}</em></h1></div><p>{p.intro}</p></div><div className="case-feature"><div className="case-feature-copy"><span>THE RESULT</span><h2>{p.result.map(x=><span key={x}>{x}<br/></span>)}</h2><div className="case-stats">{p.stats.map(([n,l])=><div key={l}><b>{n}</b><small>{l}</small></div>)}</div></div><div className="case-feature-art"><img src={`/projects/${p.folder}/${p.images[0]}`} alt={`${p.eyebrow} platform`}/><img src={`/projects/${p.folder}/${p.images[1]}`} alt={`${p.eyebrow} workflow`}/><span>{p.note}</span></div></div></section><section className="case-story"><span className="eyebrow">{p.story[0]}</span><h2>{p.story[1]}<br/><em>{p.story[2]}</em></h2><p>Explore the product journey. Use the arrows, dots, or the neighbouring screens to move through the experience.</p><Showcase project={p}/></section><section className="case-outcomes">{p.outcomes.map(([Icon,t,x])=><article key={t}><Icon/><h3>{t}</h3><p>{x}</p></article>)}</section><section className="next-project"><div><span className="eyebrow">NEXT PROJECT · {p.next[0]}</span><h2>{p.next[1]}</h2></div><Link className="button light" to={p.next[2]}>View project <ArrowRight/></Link></section></div>}
